/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PersonaController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import vista.modeloTabla.ModeloTablaPersona;
import vista.utilidades.Utilidades;

/**
 *
 * @author Iván González
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private PersonaController pc;
    private ModeloTablaPersona modeloTabla = new ModeloTablaPersona();
    private Integer fila = -1;
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarPracticas();
        cargarCombo();
        cargarTabla();
        cargarEditarPersona();
        setLocationRelativeTo(this);
    }

    private void cargarCombo(){
        Utilidades.cargarCombogenero(cbxGenero);
    }
    
    private void cargarTabla(){
        if(pc != null){
            modeloTabla.setPersonas(pc.getPersonas());
            tblPersonas.setModel(modeloTabla);
            tblPersonas.updateUI();
            jPanel3.setVisible(true);
        } else jPanel3.setVisible(false);
    }
    
    private void cargarEditarPersona(){
        if(pc != null){
            jPanel2.setVisible(true);
        } else jPanel2.setVisible(false);
    }
    
    private void cargarPracticas(){
        if(pc != null){
            jPanel5.setVisible(true);
        } else jPanel5.setVisible(false);
    }
    
    private void limpiar(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtFechaNacimiento.setText("");
        cbxGenero.setSelectedIndex(0);
        cargarTabla();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox<>();
        txtFechaNacimiento = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxNroPersonas = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPracticas = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Valores Persona"));
        jPanel2.setLayout(null);

        jLabel2.setText("Genero:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 120, 70, 16);

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 40, 70, 16);

        jLabel4.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 160, 120, 16);

        jLabel5.setText("Apellido:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 80, 70, 16);
        jPanel2.add(txtNombre);
        txtNombre.setBounds(130, 30, 160, 30);
        jPanel2.add(txtApellido);
        txtApellido.setBounds(130, 70, 160, 30);

        jPanel2.add(cbxGenero);
        cbxGenero.setBounds(130, 110, 160, 30);

        txtFechaNacimiento.setToolTipText("dd/mm/yyyy");
        jPanel2.add(txtFechaNacimiento);
        txtFechaNacimiento.setBounds(130, 150, 160, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(40, 190, 90, 22);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar);
        btnActualizar.setBounds(150, 190, 90, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 300, 310, 220);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));
        jPanel3.setLayout(null);

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonas);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 700, 210);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 60, 720, 240);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas"));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(null);

        jLabel1.setText("Número de Personas");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(30, 20, 150, 16);

        cbxNroPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jPanel4.add(cbxNroPersonas);
        cbxNroPersonas.setBounds(180, 20, 72, 22);

        btnCrear.setText("CREAR ");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel4.add(btnCrear);
        btnCrear.setBounds(300, 20, 75, 22);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 720, 50);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Prácticas"));
        jPanel5.setLayout(null);

        txtPracticas.setEditable(false);
        txtPracticas.setColumns(20);
        txtPracticas.setRows(5);
        jScrollPane2.setViewportView(txtPracticas);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(20, 30, 360, 170);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(330, 300, 400, 220);

        jMenu1.setText("File");

        jMenuItem1.setText("GUARDAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("CARGAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        crearArregloPersona();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if(!pc.getPersona().getNombre().equalsIgnoreCase(PersonaController.VALORDEFECTO)){
            Integer i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea cambiar la información?");
            if(i == JOptionPane.OK_OPTION){
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                 LocalDate fechaNacimiento = LocalDate.parse(txtFechaNacimiento.getText(), formatter);
                if (fechaNacimiento.isAfter(LocalDate.now()) || fechaNacimiento.isBefore(LocalDate.of(1875, 2, 21))){
                    JOptionPane.showMessageDialog(this, "La fecha ingresada no es correcta", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    actualizarInfoPersona();
                    limpiar();
                    jPanel2.setVisible(false);
                    jPanel5.setVisible(false);
                } 
            }
        } else {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fechaNacimiento = LocalDate.parse(txtFechaNacimiento.getText(), formatter);
            if (fechaNacimiento.isAfter(LocalDate.now()) || fechaNacimiento.isBefore(LocalDate.of(1875, 2, 21))){
                JOptionPane.showMessageDialog(this, "La fecha ingresada no es correcta", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
            actualizarInfoPersona();
            limpiar();
            jPanel2.setVisible(false);
            jPanel5.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasMouseClicked
        // TODO add your handling code here:
        Utilidades.seleccionarPersona(tblPersonas, txtPracticas);
        fila = tblPersonas.getSelectedRow();
        if(fila >= 0){
            pc.setPersona(modeloTabla.getPersonas()[fila]);
            txtNombre.setText(pc.getPersona().getNombre());
            txtApellido.setText(pc.getPersona().getApellido());
            txtFechaNacimiento.setText(pc.getPersona().getFechaNacimiento());
            cbxGenero.setSelectedItem(pc.getPersona().getGenero());
            txtPracticas.setText(pc.getPersona().getPracticas());
            cargarEditarPersona();
            cargarPracticas();
        } else JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
       
    }//GEN-LAST:event_tblPersonasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(pc != null){
            if(Utilidades.guardarJson(pc.getPersonas())){
                JOptionPane.showMessageDialog(this, "Se ha generado el fichero", "Ok", JOptionPane.INFORMATION_MESSAGE);
            } else JOptionPane.showMessageDialog(this, "No se generó el fichero", "Error", JOptionPane.ERROR_MESSAGE);
        } else JOptionPane.showMessageDialog(this, "Debe generar una persona", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        pc = new PersonaController(1);
        pc.setPersonas(Utilidades.cargarJson());
        if(pc.getPersonas() != null){
            btnCrear.setEnabled(false);
            cargarTabla();
        } else JOptionPane.showMessageDialog(this, "No se pudo cargar", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void actualizarInfoPersona(){
        pc.getPersona().setNombre(txtNombre.getText());
        pc.getPersona().setApellido(txtApellido.getText());
        pc.getPersona().setGenero(Utilidades.getGeneroCombo(cbxGenero).toString());
        try {
               pc.getPersona().setFechaNacimiento(txtFechaNacimiento.getText());
               pc.getPersona().setEdad(pc.calcularEdad(pc.getPersona()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        pc.getPersona().setClasificacion(pc.clasificarPorEdad(pc.getPersona()));
        
    }
    
    private void crearArregloPersona(){
        pc = new PersonaController(Integer.parseInt(cbxNroPersonas.getSelectedItem().toString()));
        btnCrear.setEnabled(false);
        cargarTabla();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
                
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxNroPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static final javax.swing.JTable tblPersonas = new javax.swing.JTable();
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtPracticas;
    // End of variables declaration//GEN-END:variables
}


